title: My Portfolio
author: Ian Van Harten
email: ianvharten@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio page for Ian Van Harten, coding student in the IT Innovation and Design program at Conestoga College.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ianvanharten # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
